### ISSUE TITLE
Bug: Clicking away from modal causes modal to close

### ISSUE THREAD

**Issue by energydev** [energydev/the-librarians-episode-selector#1]
For the modals, clicking elsewhere on the screen causes the modal to close.

**Comment by designBuildShipSoftware** [comment]
What do you want it to do? Do you want the modals to keep open while clicking elsewhere on the screen?

**Comment by energydev** [comment]
@designBuildShipSoftware new design of this application has made this bug obsolete. Previously, the select by season and other criteria were on a modal which when closed would popup a modal selecting the episode. Since there are no longer criteria modals, the behavior of closing the episode selection modal when clicking off would be considered correct. I'll go ahead and close this issue. Thanks for reaching out.

**Comment by energydev** [comment]
Closing obsolete issue.
